name: todo_list_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  flutter_svg: 2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/images/
   - assets/icons/

  fonts:
   - family: UniversoBold
     fonts:
       - asset: assets/fonts/Outfit-Regular.ttf
         weight: 400
       - asset: assets/fonts/Outfit-Medium.ttf
         weight: 500
       - asset: assets/fonts/Outfit-SemiBold.ttf
         weight: 600
       - asset: assets/fonts/Outfit-Bold.ttf
         weight: 700